### ISSUE TITLE
Duplicate recipes upon multiple edits

### ISSUE THREAD

**Issue by lothar243** [bry012/RecipePartDeux#17]
leaving the edit screen open and editing a recipe multiple times actually duplicates a recipe

**Comment by bry012** [comment]
Changing recipeSelected in the RecipeListPanel to null after the save button is clicked seemed to fix this issue. Edits to the communication with the database should still probably be made i.e. change from delete and insert to update.

**Comment by lothar243** [comment]
The changes have been made on my commit two days ago (10/8/14). Technically I am still calling a delete/insert statement, but now the recipe ID is kept the same, and further changes will effect the same item.
